sudo: required
services:
  - docker

before_install:
  - docker build -t shakils/react-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true shakils/react-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-057619526684"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
